# AI Learning Tutor - Full Stack Deployment
version: '3.8'

services:
  # FastAPI Backend
  backend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./chroma_data:/app/chroma_data
    environment:
      - DATABASE_URL=sqlite:///app/data/ai_tutor.db
      - CHROMA_DB_PATH=/app/chroma_data
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama
    restart: unless-stopped

  # Ollama Service (Local LLM)
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    command: ["ollama", "serve"]

  # React Frontend (optional - can be served separately)
  frontend:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm start"
    depends_on:
      - backend
    restart: unless-stopped

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

volumes:
  ollama_data:
